import { Property, Agent } from './types';

export const translations = {
  kg: {
    brandName: "My Home Bishkek",
    tagline: "Кыялыңыздагы үйдү биз менен табыңыз",
    searchPlaceholder: "Район, көчө же серия боюнча издөө...",
    buy: "Сатып алуу",
    rent: "Ижарага алуу",
    all: "Баары",
    district: "Район",
    price: "Баасы",
    rooms: "Бөлмөлөр",
    series: "Сериясы",
    reset: "Тазалоо",
    usd: "$",
    kgs: "сом",
    m2: "м²",
    floor: "Кабат",
    outOf: "кабаттан",
    details: "Кененирээк",
    contactAgent: "Агентке жазуу",
    aboutUs: "Биз жөнүндө",
    ourAgents: "Биздин агенттер",
    calculator: "Ипотека калькулятору",
    propertyValue: "Мүлктүн баасы",
    downPayment: "Баштапкы төлөм",
    interestRate: "Жылдык пайыз",
    loanTerm: "Мөөнөтү (жыл)",
    monthlyPayment: "Айлык төлөм",
    aiAssistant: "My Home AI Кеңешчи",
    aiDescription: "Бишкек шаарындагы кыймылсыз мүлк, баалар, райондор жана ипотека боюнча суроолоруңузга жооп берет.",
    aiPlaceholder: "Сурооңузду жазыңыз (мис: Жалда 2 бөлмөлүү батирлердин баасы кандай?)...",
    contactTitle: "Арыз калтыруу / Көрүүгө жазылуу",
    name: "Атыңыз",
    phone: "Телефон номериңиз",
    email: "E-mail (милдеттүү эмес)",
    message: "Кабар же сурооңуз",
    submit: "Жөнөтүү",
    favorites: "Тандалган мүлктөр",
    noFavorites: "Азырынча тандалган мүлктөр жок.",
    popularListings: "Популярдуу сунуштар",
    newListing: "Жарнама кошуу",
    listingType: "Келишим түрү",
    address: "Дареги",
    description: "Мүнөздөмөсү",
    successSent: "Сиздин билдирүүңүз ийгиликтүү жөнөтүлдү! Агент жакында сиз менен байланышат.",
    addSuccess: "Сиздин жарнамаңыз текшерүүгө жөнөтүлдү. Рахмат!",
    close: "Жабуу",
    districtLabel: "Район тандаңыз",
    roomsLabel: "Бөлмө саны",
    seriesLabel: "Сериясы",
    usdKgsToggle: "Валюта",
    mortgageTitle: "Ипотеканы эсептөө",
    calcResult: "Божомолдуу айлык төлөм:",
    contactPrompt: "Мүлктү көрүү же суроо берүү үчүн агент менен байланышыңыз:",
    whatsAppChat: "WhatsApp'та жазуу",
    callPhone: "Чалуу",
    legalAddress: "Бишкек ш., Чүй проспектиси 125",
    workingHours: "Жумуш убактысы: 09:00 - 19:00",
    allRightsReserved: "Бардык укуктар корголгон.",
    aboutText: "My Home Bishkek — бул Бишкек шаарындагы кыймылсыз мүлк сатып алуу, сатуу жана ижарага берүү боюнча заманбап кызмат көрсөтүүчү агенттик. Биз сизге эң ыңгайлуу батирлерди, үйлөрдү жана коммерциялык объекттерди табууга жардам беребиз. Биздин AI-кеңешчибиз кардарларыбызга 24/7 убакытта баалар, райондор жана ипотека шарттары тууралуу маалымат бере алат."
  },
  ru: {
    brandName: "My Home Bishkek",
    tagline: "Найдите дом своей мечты вместе с нами",
    searchPlaceholder: "Поиск по району, улице или серии...",
    buy: "Купить",
    rent: "Аренда",
    all: "Все",
    district: "Район",
    price: "Цена",
    rooms: "Комнаты",
    series: "Серия",
    reset: "Сбросить",
    usd: "$",
    kgs: "сом",
    m2: "м²",
    floor: "Этаж",
    outOf: "из",
    details: "Подробнее",
    contactAgent: "Написать агенту",
    aboutUs: "О нас",
    ourAgents: "Наши агенты",
    calculator: "Ипотечный калькулятор",
    propertyValue: "Стоимость имущества",
    downPayment: "Первоначальный взнос",
    interestRate: "Годовая ставка",
    loanTerm: "Срок (лет)",
    monthlyPayment: "Ежемесячный платеж",
    aiAssistant: "My Home AI Консультант",
    aiDescription: "Ответит на вопросы по недвижимости, ценам, районам Бишкека и ипотечным условиям.",
    aiPlaceholder: "Задайте ваш вопрос (напр: какие цены на 2-комнатные квартиры в Джале?)...",
    contactTitle: "Оставить заявку / Записаться на показ",
    name: "Ваше имя",
    phone: "Номер телефона",
    email: "E-mail (необязательно)",
    message: "Сообщение или вопрос",
    submit: "Отправить",
    favorites: "Избранные объекты",
    noFavorites: "Пока нет избранных объектов.",
    popularListings: "Популярные предложения",
    newListing: "Добавить объявление",
    listingType: "Тип сделки",
    address: "Адрес",
    description: "Описание",
    successSent: "Ваше сообщение успешно отправлено! Агент свяжется с вами в ближайшее время.",
    addSuccess: "Ваше объявление отправлено на модерацию. Спасибо!",
    close: "Закрыть",
    districtLabel: "Выберите район",
    roomsLabel: "Количество комнат",
    seriesLabel: "Серия",
    usdKgsToggle: "Валюта",
    mortgageTitle: "Расчет ипотеки",
    calcResult: "Ориентировочный ежемесячный платеж:",
    contactPrompt: "Свяжитесь с агентом для показа или уточнения деталей:",
    whatsAppChat: "Написать в WhatsApp",
    callPhone: "Позвонить",
    legalAddress: "г. Бишкек, проспект Чуй 125",
    workingHours: "Время работы: 09:00 - 19:00",
    allRightsReserved: "Все права защищены.",
    aboutText: "My Home Bishkek — современное агентство недвижимости в Бишкеке, специализирующееся на покупке, продаже и аренде жилой и коммерческой недвижимости. Мы помогаем найти лучшие квартиры, дома и офисы с юридической гарантией безопасности. Наш уникальный AI-консультант доступен 24/7, чтобы подсказать актуальные цены, особенности серий жилья и условия кредитования."
  },
  en: {
    brandName: "My Home Bishkek",
    tagline: "Find your dream home with us",
    searchPlaceholder: "Search by district, street, or series...",
    buy: "Buy",
    rent: "Rent",
    all: "All",
    district: "District",
    price: "Price",
    rooms: "Rooms",
    series: "Series",
    reset: "Reset",
    usd: "$",
    kgs: "KGS",
    m2: "m²",
    floor: "Floor",
    outOf: "of",
    details: "Details",
    contactAgent: "Contact Agent",
    aboutUs: "About Us",
    ourAgents: "Our Agents",
    calculator: "Mortgage Calculator",
    propertyValue: "Property Value",
    downPayment: "Down Payment",
    interestRate: "Annual Interest",
    loanTerm: "Term (Years)",
    monthlyPayment: "Monthly Payment",
    aiAssistant: "My Home AI Consultant",
    aiDescription: "Answers your questions about real estate, prices, districts in Bishkek, and mortgage terms.",
    aiPlaceholder: "Ask your question (e.g., what are the prices for 2-room apartments in Jal?)...",
    contactTitle: "Submit Request / Book a Viewing",
    name: "Your Name",
    phone: "Phone Number",
    email: "E-mail (optional)",
    message: "Message or Question",
    submit: "Send",
    favorites: "Favorites",
    noFavorites: "No favorite properties yet.",
    popularListings: "Popular Offers",
    newListing: "Add Listing",
    listingType: "Deal Type",
    address: "Address",
    description: "Description",
    successSent: "Your message has been successfully sent! An agent will contact you shortly.",
    addSuccess: "Your listing has been submitted for moderation. Thank you!",
    close: "Close",
    districtLabel: "Select district",
    roomsLabel: "Number of rooms",
    seriesLabel: "Series",
    usdKgsToggle: "Currency",
    mortgageTitle: "Calculate Mortgage",
    calcResult: "Estimated Monthly Payment:",
    contactPrompt: "Contact an agent to view properties or ask questions:",
    whatsAppChat: "Chat on WhatsApp",
    callPhone: "Call",
    legalAddress: "125 Chuy Ave, Bishkek",
    workingHours: "Working hours: 09:00 - 19:00",
    allRightsReserved: "All rights reserved.",
    aboutText: "My Home Bishkek is a modern real estate agency in Bishkek, specializing in the purchase, sale, and lease of residential and commercial real estate. We help you find the best apartments, houses, and offices with legal safety guarantees. Our unique AI Consultant is available 24/7 to provide information on current prices, building series characteristics, and mortgage terms."
  },
  ko: {
    brandName: "My Home Bishkek",
    tagline: "우리와 함께 꿈의 집을 찾아보세요",
    searchPlaceholder: "지역, 거리 또는 시리즈 검색...",
    buy: "매매",
    rent: "임대",
    all: "전체",
    district: "지역",
    price: "가격",
    rooms: "방 수",
    series: "시리즈",
    reset: "초기화",
    usd: "$",
    kgs: "솜",
    m2: "m²",
    floor: "층",
    outOf: "중",
    details: "상세 정보",
    contactAgent: "에이전트 문의",
    aboutUs: "회사 소개",
    ourAgents: "소속 에이전트",
    calculator: "주택 담보 대출 계산기",
    propertyValue: "매물 가격",
    downPayment: "선납금",
    interestRate: "연이율",
    loanTerm: "대출 기간 (년)",
    monthlyPayment: "월 납입금",
    aiAssistant: "My Home AI 상담사",
    aiDescription: "비슈케크 부동산, 시세, 선호 지역 및 담보 대출 조건에 관한 질문에 답변해 드립니다.",
    aiPlaceholder: "질문을 입력하세요 (예: 잘 지역의 방 2개 아파트 시세는 어떻게 되나요?)...",
    contactTitle: "상담 요청 / 매물 투어 예약",
    name: "성함",
    phone: "전화번호",
    email: "이메일 (선택 사항)",
    message: "문의 내용 또는 질문",
    submit: "전송하기",
    favorites: "관심 매물",
    noFavorites: "관심 매물로 등록된 항목이 없습니다.",
    popularListings: "인기 추천 매물",
    newListing: "매물 등록",
    listingType: "거래 방식",
    address: "주소",
    description: "매물 설명",
    successSent: "문의 메시지가 성공적으로 전송되었습니다! 에이전트가 곧 연락드리겠습니다.",
    addSuccess: "등록 신청하신 매물이 관리자 검토 단계로 전송되었습니다. 감사합니다!",
    close: "닫기",
    districtLabel: "지역 선택",
    roomsLabel: "방 개수",
    seriesLabel: "시리즈",
    usdKgsToggle: "통화 선택",
    mortgageTitle: "담보 대출 계산",
    calcResult: "예상 월 납입금:",
    contactPrompt: "투어를 원하시거나 질문이 있으시면 에이전트에게 직접 문의하세요:",
    whatsAppChat: "WhatsApp으로 연락하기",
    callPhone: "전화 상담",
    legalAddress: "비슈케크시 추이 대로 125",
    workingHours: "업무 시간: 09:00 - 19:00",
    allRightsReserved: "모든 권리 보유.",
    aboutText: "My Home Bishkek은 비슈케크에서 주거 및 상업용 부동산의 매매, 전월세 임대를 전문으로 하는 현대적인 부동산 에이전시입니다. 법적인 안전 보장과 함께 최상의 아파트, 주택 및 사무실을 찾을 수 있도록 도와드립니다. 자체 AI 상담사가 24시간 연중무휴로 대기하여 현재 가격, 주택 시리즈 특성 및 대출 조건에 대해 상세히 안내해 드립니다."
  }
};

export const bishkekDistricts = [
  { id: 'all', kg: 'Баардык райондор', ru: 'Все районы', en: 'All districts', ko: '모든 지역' },
  { id: 'center', kg: 'Борбор (Центр)', ru: 'Центр', en: 'Center', ko: '시내 중심' },
  { id: 'asanbay', kg: 'Асанбай / 12-мкр', ru: 'Асанбай / 12-мкр', en: 'Asanbay / 12th microdistrict', ko: '아산바이 / 12 구역' },
  { id: 'jal', kg: 'Жал (Жал-23, 15, 29)', ru: 'Джал (Джал-23, 15, 29)', en: 'Jal (Jal-23, 15, 29)', ko: '잘 (잘-23, 15, 29)' },
  { id: 'vostok5', kg: 'Восток-5 / Аламедин-1', ru: 'Восток-5 / Аламедин-1', en: 'Vostok-5 / Alamedin-1', ko: '보스토크-5 / 알라메딘-1' },
  { id: 'kokzhar', kg: 'Көк-Жар / Түндүк', ru: 'Кок-Жар / Тунгуч', en: 'Kok-Zhar / Tunguch', ko: '콕자르 / 퉁구치' },
  { id: 'mkr', kg: 'Кичирайондор (3, 4, 5, 6, 7, 8, 9, 10)', ru: 'Микрорайоны (3, 4, 5, 6, 7, 8, 9, 10)', en: 'Microdistricts (3, 4, 5, 6, 7, 8, 9, 10)', ko: '미소지구 (3, 4, 5, 6, 7, 8, 9, 10)' },
  { id: 'piramida', kg: 'Ала-Тоо / Түштүк дарбаза', ru: 'Южные Магистрали / Южные ворота', en: 'Southern Arteries / Southern Gates', ko: '남부 대로 / 남문 지역' }
];

export const housingSeries = [
  { id: 'all', kg: 'Бардык сериялар', ru: 'Все серии', en: 'All series', ko: '모든 시리즈' },
  { id: 'elite', kg: 'Элитка (Жаңы курулуш)', ru: 'Элитка (Новостройка)', en: 'Elite (New building)', ko: '엘리트카 (신축)' },
  { id: '104', kg: '104-серия', ru: '104-серия', en: '104-series', ko: '104-시리즈' },
  { id: '105', kg: '105-серия', ru: '105-серия', en: '105-series', ko: '105-시리즈' },
  { id: '106', kg: '106-серия', ru: '106-серия', en: '106-series', ko: '106-시리즈' },
  { id: 'individual', kg: 'Индивидуалдык долбоор', ru: 'Индивидуальный проект', en: 'Individual project', ko: '개별 설계 프로젝트' }
];

export const agents: Agent[] = [
  {
    id: 'agent-1',
    name: 'Зарена',
    roleKg: 'Башкы директор',
    roleRu: 'Генеральный директор',
    roleEn: 'General Director',
    roleKo: '대표이사 / CEO',
    phone: '+996 995 288 288',
    whatsApp: 'https://wa.me/996995288288',
    email: 'zarena@myhome.kg',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200&h=200'
  },
  {
    id: 'agent-2',
    name: 'Гульзада',
    roleKg: 'Юрист',
    roleRu: 'Юрист',
    roleEn: 'Legal Counsel',
    roleKo: '법률 고문 / 변호사',
    phone: '+996 554 757 455',
    whatsApp: 'https://wa.me/996554757455',
    email: 'gulzada@myhome.kg',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200&h=200'
  },
  {
    id: 'agent-3',
    name: 'Абдыманап',
    roleKg: 'Алып сатуу бөлүмүнүн менеджери',
    roleRu: 'Менеджер отдела продаж',
    roleEn: 'Sales Manager',
    roleKo: '분양 / 매매 영업 매니저',
    phone: '+996 774 276 666',
    whatsApp: 'https://wa.me/996774276666',
    email: 'abdymanap@myhome.kg',
    photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=200&h=200'
  },
  {
    id: 'agent-4',
    name: 'Кундуз',
    roleKg: 'Түштүк Кореядагы жарандар үчүн менеджер',
    roleRu: 'Менеджер для граждан в Южной Корее',
    roleEn: 'Manager for citizens in South Korea',
    roleKo: '대한민국 거주 교민 담당 매니저',
    phone: '+82 10 8096 3369',
    whatsApp: 'https://wa.me/821080963369',
    email: 'kunduz@myhome.kg',
    photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200&h=200'
  },
  {
    id: 'agent-5',
    name: 'Айзада',
    roleKg: 'Орусиядагы жарандар үчүн менеджер',
    roleRu: 'Менеджер для граждан в России',
    roleEn: 'Manager for citizens in Russia',
    roleKo: '러시아 거주 교민 담당 매니저',
    phone: '+996 551 497 776',
    whatsApp: 'https://wa.me/996551497776',
    email: 'aizada@myhome.kg',
    photo: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=200&h=200'
  }
];

export const initialProperties: Property[] = [
  {
    id: 'prop-1',
    titleKg: 'Асанбайдагы заманбап 3 бөлмөлүү элиттик батир',
    titleRu: 'Современная 3-комнатная элитная квартира в Асанбае',
    titleEn: 'Modern 3-room elite apartment in Asanbay',
    titleKo: '아산바이 구역의 현대적인 방 3개짜리 최고급 아파트',
    priceUsd: 125000,
    districtKg: 'Асанбай / 12-мкр',
    districtRu: 'Асанбай / 12-мкр',
    districtEn: 'Asanbay / 12th microdistrict',
    districtKo: '아산바이 / 12 구역',
    addressKg: 'Аалы Токомбаев көчөсү, 23/1',
    addressRu: 'ул. Аалы Токомбаева, 23/1',
    addressEn: 'Aaly Tokombaev street, 23/1',
    addressKo: '알리 토콤바예프 거리, 23/1',
    rooms: 3,
    m2: 98,
    floor: 7,
    maxFloor: 12,
    seriesKg: 'Элитка (Жаңы курулуш)',
    seriesRu: 'Элитка (Новостройка)',
    seriesEn: 'Elite (New building)',
    seriesKo: '엘리트카 (신축)',
    descriptionKg: 'Асанбай районунда, экологиялык таза түштүк аймакта жайгашкан эң сонун жаңы батир. Жогорку сапаттагы курулуш, коопсуздук, толук эмеректери жана тиричилик техникалары менен. Терезесинен тоолор кооз көрүнөт.',
    descriptionRu: 'Превосходная квартира в экологически чистом районе Асанбай. Качественный ремонт, закрытая охраняемая территория, полностью меблирована и укомплектована техникой. Панорамный вид на горы.',
    descriptionEn: 'An excellent new apartment located in the ecologically clean southern district of Asanbay. High-quality construction, full security, fully furnished and equipped with premium appliances. Beautiful panoramic mountain view.',
    descriptionKo: '친환경적인 남부 아산바이 지역에 위치한 훌륭한 신축 아파트입니다. 고급 자재 시공, 철저한 보안, 가구 및 프리미엄 가전 완비. 탁 트인 산 전망이 아름답습니다.',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800',
    type: 'buy',
    isPopular: true,
    addedDate: '2026-06-15',
    agentId: 'agent-1',
    lat: 42.8182,
    lng: 74.6201
  },
  {
    id: 'prop-2',
    titleKg: 'Жал кичирайонунда 2 бөлмөлүү батир (106-серия)',
    titleRu: '2-комнатная квартира в Джале (106-серия)',
    titleEn: '2-room apartment in Jal (106-series)',
    titleKo: '잘 지역의 방 2개짜리 아파트 (106-시리즈)',
    priceUsd: 68500,
    districtKg: 'Жал (Жал-23, 15, 29)',
    districtRu: 'Джал (Джал-23, 15, 29)',
    districtEn: 'Jal (Jal-23, 15, 29)',
    districtKo: '잘 (잘-23, 15, 29)',
    addressKg: 'Тыналиев көчөсү, 15',
    addressRu: 'ул. Тыналиева, 15',
    addressEn: 'Tynalieva street, 15',
    addressKo: '티날리에바 거리, 15',
    rooms: 2,
    m2: 54,
    floor: 4,
    maxFloor: 9,
    seriesKg: '106-серия',
    seriesRu: '106-серия',
    seriesEn: '106-series',
    seriesKo: '106-시리즈',
    descriptionKg: 'Жал кичирайонундагы эң популярдуу 106-сериядагы батир. Жакшы абалда, терезелери пластик, лоджиясы жылууланган. Күн тийген тарап, айланасында бала бакчалар, мектептер жана супермаркеттер бар.',
    descriptionRu: 'Квартира популярной 106 серии в микрорайоне Джал. Хорошее состояние, пластиковые окна, лоджия утеплена. Солнечная сторона. Отличная инфраструктура: школы, детсады, супермаркеты.',
    descriptionEn: 'An apartment of the popular 106 series in the Jal microdistrict. Good condition, plastic windows, insulated loggia. Sunny side. Excellent infrastructure: schools, kindergartens, supermarkets in close proximity.',
    descriptionKo: '잘 미소지구에 위치한 인기 있는 106 시리즈 아파트입니다. 관리 상태 양호, 이중창 샷시, 단열 발코니 완비. 남향/채광 우수. 인근에 학교, 유치원, 대형 마트 등 우수한 생활 인프라.',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800',
    type: 'buy',
    isPopular: true,
    isBarter: true,
    addedDate: '2026-06-20',
    agentId: 'agent-2',
    lat: 42.8425,
    lng: 74.5644
  },
  {
    id: 'prop-3',
    titleKg: 'Шаардын борборунда жайгашкан 1 бөлмөлүү студия батир',
    titleRu: '1-комнатная квартира-студия в самом центре города',
    titleEn: '1-room studio apartment in the city center',
    titleKo: '시내 중심가에 위치한 원룸형 스튜디오 아파트',
    priceUsd: 52000,
    districtKg: 'Борбор (Центр)',
    districtRu: 'Центр',
    districtEn: 'Center',
    districtKo: '시내 중심',
    addressKg: 'Чүй проспектиси / Абдрахманов',
    addressRu: 'проспект Чуй / ул. Абдрахманова',
    addressEn: 'Chuy Avenue / Abdrakhmanov',
    addressKo: '추и 대로 / 압драх마노프 거리',
    rooms: 1,
    m2: 42,
    floor: 5,
    maxFloor: 14,
    seriesKg: 'Элитка (Жаңы курулуш)',
    seriesRu: 'Элитка (Новостройка)',
    seriesEn: 'Elite (New building)',
    seriesKo: '엘리트카 (신축)',
    descriptionKg: 'Шаардын борборунда, эң ыңгайлуу жерде жайгашкан заманбап дизайндуу студия. Студенттер же жаш жубайлар үчүн эң сонун вариант. Жогорку ылдамдыктагы интернет, консьерж, видеокөзөмөл.',
    descriptionRu: 'Современная студия в самом центре столицы. Прекрасный вариант для молодой пары или сдачи в аренду. Вся инфраструктура в шаговой доступности. Круглосуточная охрана, консьерж, паркинг.',
    descriptionEn: 'A modern designer studio apartment in the very center of the capital. Excellent option for students, young couples, or rental investment. High-speed internet, concierge service, 24/7 security and video surveillance.',
    descriptionKo: '수도 중심가에 위치한 세련된 인테리어의 스튜디오입니다. 학생, 신혼부부 또는 임대 투자용으로 적극 추천합니다. 초고속 인터넷, 컨시어지 서비스, 24시간 보안 및 CCTV 가동.',
    image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=800',
    type: 'buy',
    isPopular: false,
    addedDate: '2026-06-25',
    agentId: 'agent-2',
    lat: 42.8778,
    lng: 74.6147
  },
  {
    id: 'prop-4',
    titleKg: 'Ижарага берилет: Асанбайдагы 2 бөлмөлүү люкс батир',
    titleRu: 'Аренда: 2-комнатная люкс квартира в Асанбае',
    titleEn: 'For Rent: 2-room luxury apartment in Asanbay',
    titleKo: '임대: 아산바이 구역의 방 2개짜리 럭셔리 아파트',
    priceUsd: 850,
    districtKg: 'Асанбай / 12-мкр',
    districtRu: 'Асанбай / 12-мкр',
    districtEn: 'Asanbay / 12th microdistrict',
    districtKo: '아산바이 / 12 구역',
    addressKg: 'Сухэ-Батор көчөсү, 5',
    addressRu: 'ул. Сухэ-Батора, 5',
    addressEn: 'Sukhe-Bator street, 5',
    addressKo: '수헤바토르 거리, 5',
    rooms: 2,
    m2: 75,
    floor: 8,
    maxFloor: 10,
    seriesKg: 'Элитка (Жаңы курулуш)',
    seriesRu: 'Элитка (Новостройка)',
    seriesEn: 'Elite (New building)',
    seriesKo: '엘리트카 (신축)',
    descriptionKg: 'Узак мөөнөткө гана берилет. Кымбат баалуу дизайнердик оңдоп-түзөө, толугу менен кондиционерленген, бардык керектүү техникалар орнотулган. Күзөтүлгөн унаа токтотуучу жайы бар.',
    descriptionRu: 'Сдается на длительный срок. Дорогой дизайнерский ремонт, автономное отопление, кондиционер, посудомоечная машина, тёплый пол. Закрытый охраняемый двор со своей детской площадкой.',
    descriptionEn: 'Available for long-term lease only. Expensive designer renovation, fully air-conditioned, equipped with all necessary home appliances. Gated territory with reserved parking slot and play area.',
    descriptionKo: '장기 임대 전용 매물입니다. 최고급 자재 디자이너 인테리어, 풀 에어컨 시스템, 필수 가전 완비. 주차 공간이 지정된 안전한 펜스 단지 및 놀이터.',
    image: 'https://images.unsplash.com/photo-1502672023488-70e25813eb80?auto=format&fit=crop&q=80&w=800',
    type: 'rent',
    isPopular: true,
    addedDate: '2026-06-28',
    agentId: 'agent-1',
    lat: 42.8225,
    lng: 74.6212
  },
  {
    id: 'prop-5',
    titleKg: 'Көк-Жарда жайгашкан чоң 3 бөлмөлүү батир',
    titleRu: 'Просторная 3-комнатная квартира в Кок-Жаре',
    titleEn: 'Spacious 3-room apartment in Kok-Zhar',
    titleKo: '콕자르 지역의 넓은 방 3개짜리 아파트',
    priceUsd: 84000,
    districtKg: 'Көк-Жар / Түндүк',
    districtRu: 'Кок-Жар / Тунгуч',
    districtEn: 'Kok-Zhar / Tunguch',
    districtKo: '콕자르 / 퉁구치',
    addressKg: 'Шабдан Баатыр көчөсү, 82',
    addressRu: 'ул. Шабдан Баатыра, 82',
    addressEn: 'Shabdan Baatyr street, 82',
    addressKo: '샤브단 바티르 거리, 82',
    rooms: 3,
    m2: 85,
    floor: 3,
    maxFloor: 9,
    seriesKg: '105-серия',
    seriesRu: '105-серия',
    seriesEn: '105-series',
    seriesKo: '105-시리즈',
    descriptionKg: 'Көк-Жар конушунун жанындагы эң сонун райондо. Бөлмөлөрү өз-өзүнчө ажыратылган, кең ашкана, эки чоң лоджиясы бар. Ичи таза, косметический ремонт кылынган. Документтери толук таза.',
    descriptionRu: 'Просторная светлая квартира в районе Кок-Жар. Планировка раздельная, большая кухня, две застекленные лоджии. В хорошем косметическом состоянии. Документы готовы к сделке.',
    descriptionEn: 'Spacious, bright apartment in Kok-Zhar. Separate rooms, a large kitchen, two glazed loggias. Good cosmetic condition. All documents are verified and ready for transaction.',
    descriptionKo: '콕자르 지역의 채광 좋고 넓은 아파트입니다. 각 방 독립 구조, 넓은 주방, 유리 섀시 발코니 2개. 깔끔한 도배/장판 상태. 서류 완비 즉시 거래 가능.',
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=800',
    type: 'buy',
    isPopular: false,
    addedDate: '2026-06-18',
    agentId: 'agent-3',
    lat: 42.8465,
    lng: 74.6402
  },
  {
    id: 'prop-6',
    titleKg: 'Восток-5 кичирайонунда 3 бөлмөлүү батир (105-серия)',
    titleRu: '3-комнатная квартира в Восток-5 (105-серия)',
    titleEn: '3-room apartment in Vostok-5 (105-series)',
    titleKo: '보스토크-5 구역의 방 3개짜리 아파트 (105-시리즈)',
    priceUsd: 76000,
    districtKg: 'Восток-5 / Аламедин-1',
    districtRu: 'Восток-5 / Аламедин-1',
    districtEn: 'Vostok-5 / Alamedin-1',
    districtKo: '보스토크-5 / 알라메딘-1',
    addressKg: 'Мамбетов көчөсү, 14',
    addressRu: 'ул. Мамбетова, 14',
    addressEn: 'Mambetova street, 14',
    addressKo: '맘베토바 거리, 14',
    rooms: 3,
    m2: 64,
    floor: 2,
    maxFloor: 9,
    seriesKg: '105-серия',
    seriesRu: '105-серия',
    seriesEn: '105-series',
    seriesKo: '105-시리즈',
    descriptionKg: 'Восток-5 кичирайонунда, Чүй проспектисине жакын жерде жайгашкан ыңгайлуу батир. 2-кабат болгондуктан абдан ыңгайлуу. Жакында эле ремонттолгон, эмеректери жарым-жартылай калат.',
    descriptionRu: 'Комфортабельная квартира на удобном 2-м этаже в микрорайоне Восток-5. Свежий ремонт, частично остается мебель. Отличная транспортная развязка, рядом школы и детские сады.',
    descriptionEn: 'Comfortable apartment on the convenient 2nd floor in Vostok-5 microdistrict. Recently renovated, partially furnished. Excellent transport accessibility, near schools and kindergartens.',
    descriptionKo: '보스토크-5 미소지구의 로얄층인 2층 아파트입니다. 최근 부분 리모델링 완료, 일부 가구 포함. 교통 요지, 인근 초등학교 및 유치원 위치.',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800',
    type: 'buy',
    isPopular: false,
    addedDate: '2026-06-22',
    agentId: 'agent-2',
    lat: 42.8755,
    lng: 74.6360
  },
  {
    id: 'prop-7',
    titleKg: 'Ижарага берилет: Борбордо жайгашкан 1 бөлмөлүү стилдүү батир',
    titleRu: 'Аренда: Стильная 1-комнатная квартира в центре',
    titleEn: 'For Rent: Stylish 1-room apartment in the center',
    titleKo: '임대: 시내 중심가의 스타일리시한 방 1개짜리 아파트',
    priceUsd: 450,
    districtKg: 'Борбор (Центр)',
    districtRu: 'Центр',
    districtEn: 'Center',
    districtKo: '시내 중심',
    addressKg: 'Токтогул көчөсү / Исанов',
    addressRu: 'ул. Токтогула / ул. Исанова',
    addressEn: 'Toktogul street / Isanova',
    addressKo: '톡토굴 거리 / 이사노바 거리',
    rooms: 1,
    m2: 45,
    floor: 6,
    maxFloor: 12,
    seriesKg: 'Элитка (Жаңы курулуш)',
    seriesRu: 'Элитка (Новостройка)',
    seriesEn: 'Elite (New building)',
    seriesKo: '엘리트카 (신축)',
    descriptionKg: 'Заманбап элиткадан сонун батир. Жаңы эмеректер, интернет, кир жуучу машина жана толук тиричилик куралдары бар. Борбордогу ресторандар, соода борборлору жакын жерде.',
    descriptionRu: 'Уютная и современная квартира в новом элитном доме. Оборудована современной мебелью и бытовой техникой. В шаговой доступности лучшие заведения столицы, торговые центры, парки.',
    descriptionEn: 'Cozy and modern apartment in a new elite building. Equipped with modern furniture and home appliances. In walking distance to the best restaurants, malls, and parks of the capital.',
    descriptionKo: '고급 신축 주상복합 내 아늑하고 트렌디한 아파트입니다. 현대적인 가구와 고성능 가전 완비. 도보 거리에 비슈케크 맛집, 쇼핑몰, 공원 위치.',
    image: 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?auto=format&fit=crop&q=80&w=800',
    type: 'rent',
    isPopular: false,
    addedDate: '2026-06-29',
    agentId: 'agent-2',
    lat: 42.8732,
    lng: 74.5872
  },
  {
    id: 'prop-8',
    titleKg: 'Түштүк магистралында жайгашкан люкс конуш үйү',
    titleRu: 'Элитный таунхаус в районе Южной Магистрали',
    titleEn: 'Elite townhouse near Southern Arteries',
    titleKo: '남부 대로 지역의 최고급 타운하우스',
    priceUsd: 210000,
    districtKg: 'Ала-Тоо / Түштүк дарбаза',
    districtRu: 'Южные Магистрали / Южные ворота',
    districtEn: 'Southern Arteries / Southern Gates',
    districtKo: '남부 대로 / 남문 지역',
    addressKg: 'Ынтымак конушу, 12-көчө',
    addressRu: 'ж/м Ынтымак, 12-я улица',
    addressEn: 'Yntymak settlement, 12th street',
    addressKo: '은티막 주택단지, 12번가',
    rooms: 5,
    m2: 175,
    floor: 1,
    maxFloor: 3,
    seriesKg: 'Индивидуалдык долбоор',
    seriesRu: 'Индивидуальный проект',
    seriesEn: 'Individual project',
    seriesKo: '개별 설계 프로젝트',
    descriptionKg: 'Бишкектин эң престиждүү экологиялык таза районундагы 3 кабаттуу таунхаус. Өздүк чакан короосу, 2 унаалык токтотуучу орду бар. Тынч жашоо, таза аба жана тоолордун көрүнүшү.',
    descriptionRu: 'Превосходный 3-этажный таунхаус в престижной части Южной Магистрали. Собственный уютный дворик, охрана, парковка на 2 автомобиля. Прекрасная экология, чистый воздух и вид на горы.',
    descriptionEn: 'Excellent 3-story townhouse in the prestigious southern part of Bishkek. Private cozy backyard, security system, and private parking for 2 cars. Clean mountain breeze and peace.',
    descriptionKo: '비슈케크 최고 부촌인 남부 구역의 3층형 고급 타운하우스입니다. 아늑한 전용 정원, 첨단 보안 시스템, 지정 주차 2대 가능. 상쾌한 산바람과 여유로운 전원 생활.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800',
    type: 'buy',
    isPopular: true,
    addedDate: '2026-06-10',
    agentId: 'agent-3',
    lat: 42.8125,
    lng: 74.5895
  }
];
